[package]
name = "mainr"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
actix-files = "0.6"         # Add this line for serving static files
warp = "0.3"